# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hely\he\Pyprojects\Jacquard_SRC\garment_testui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import QMainWindow
from PyQt4.QtGui import QApplication

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(QMainWindow):

    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1554, 883)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btn_fix_check = QtGui.QPushButton(self.centralwidget)
        self.btn_fix_check.setObjectName(_fromUtf8("btn_fix_check"))
        self.horizontalLayout_4.addWidget(self.btn_fix_check)
        self.btn_roll_test = QtGui.QPushButton(self.centralwidget)
        self.btn_roll_test.setObjectName(_fromUtf8("btn_roll_test"))
        self.horizontalLayout_4.addWidget(self.btn_roll_test)
        self.btn_acc_test = QtGui.QPushButton(self.centralwidget)
        self.btn_acc_test.setObjectName(_fromUtf8("btn_acc_test"))
        self.horizontalLayout_4.addWidget(self.btn_acc_test)
        self.btn_test_finished = QtGui.QPushButton(self.centralwidget)
        self.btn_test_finished.setObjectName(_fromUtf8("btn_test_finished"))
        self.horizontalLayout_4.addWidget(self.btn_test_finished)
        self.btn_auto_test = QtGui.QPushButton(self.centralwidget)
        self.btn_auto_test.setObjectName(_fromUtf8("btn_auto_test"))
        self.horizontalLayout_4.addWidget(self.btn_auto_test)
        self.btn_loop_test = QtGui.QPushButton(self.centralwidget)
        self.btn_loop_test.setObjectName(_fromUtf8("btn_loop_test"))
        self.horizontalLayout_4.addWidget(self.btn_loop_test)
        self.btn_reset = QtGui.QPushButton(self.centralwidget)
        self.btn_reset.setObjectName(_fromUtf8("btn_reset"))
        self.horizontalLayout_4.addWidget(self.btn_reset)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 12, 0, 1, 2)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_3.addWidget(self.line_8, 13, 0, 1, 2)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_3.addWidget(self.line_6, 11, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_11.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.btn_press_home = QtGui.QPushButton(self.centralwidget)
        self.btn_press_home.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.btn_press_home.setObjectName(_fromUtf8("btn_press_home"))
        self.horizontalLayout_3.addWidget(self.btn_press_home)
        self.btn_roll_home = QtGui.QPushButton(self.centralwidget)
        self.btn_roll_home.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.btn_roll_home.setObjectName(_fromUtf8("btn_roll_home"))
        self.horizontalLayout_3.addWidget(self.btn_roll_home)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_28 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.horizontalLayout_3.addWidget(self.pushButton_28)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 4, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setMaximumSize(QtCore.QSize(155, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout.addWidget(self.label_13)
        self.comboBox_5 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_5.setMaximumSize(QtCore.QSize(130, 16777215))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.horizontalLayout.addWidget(self.comboBox_5)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 46))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBox_6 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.horizontalLayout.addWidget(self.comboBox_6)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.comboBox_4 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.horizontalLayout.addWidget(self.comboBox_4)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout.addWidget(self.label_15)
        self.lineEdit_9 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(153, 16777215))
        self.lineEdit_9.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout.addWidget(self.lineEdit_9)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.lineEdit_10 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(153, 16777215))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout.addWidget(self.lineEdit_10)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_3.addWidget(self.line_4, 3, 0, 1, 2)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_3.addWidget(self.line_7, 6, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lineEdit_5 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_5.setSizeIncrement(QtCore.QSize(100, 0))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_2.addWidget(self.lineEdit_5)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_2.addWidget(self.lineEdit_7)
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_2.addWidget(self.lineEdit_6)
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_save = QtGui.QPushButton(self.centralwidget)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_in10 = QtGui.QLineEdit(self.centralwidget)
        self.line_in10.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in10.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in10.setReadOnly(True)
        self.line_in10.setObjectName(_fromUtf8("line_in10"))
        self.gridLayout.addWidget(self.line_in10, 1, 3, 1, 1)
        self.line_in1 = QtGui.QLineEdit(self.centralwidget)
        self.line_in1.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.line_in1.setStyleSheet(_fromUtf8(""))
        self.line_in1.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in1.setReadOnly(True)
        self.line_in1.setObjectName(_fromUtf8("line_in1"))
        self.gridLayout.addWidget(self.line_in1, 0, 0, 1, 1)
        self.line_in14 = QtGui.QLineEdit(self.centralwidget)
        self.line_in14.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in14.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in14.setReadOnly(True)
        self.line_in14.setObjectName(_fromUtf8("line_in14"))
        self.gridLayout.addWidget(self.line_in14, 2, 1, 1, 1)
        self.lline_in4 = QtGui.QLineEdit(self.centralwidget)
        self.lline_in4.setMinimumSize(QtCore.QSize(0, 50))
        self.lline_in4.setAlignment(QtCore.Qt.AlignCenter)
        self.lline_in4.setReadOnly(True)
        self.lline_in4.setObjectName(_fromUtf8("lline_in4"))
        self.gridLayout.addWidget(self.lline_in4, 0, 3, 1, 1)
        self.line_in13 = QtGui.QLineEdit(self.centralwidget)
        self.line_in13.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in13.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in13.setObjectName(_fromUtf8("line_in13"))
        self.gridLayout.addWidget(self.line_in13, 2, 0, 1, 1)
        self.line_in2 = QtGui.QLineEdit(self.centralwidget)
        self.line_in2.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in2.setReadOnly(True)
        self.line_in2.setObjectName(_fromUtf8("line_in2"))
        self.gridLayout.addWidget(self.line_in2, 0, 1, 1, 1)
        self.line_in7 = QtGui.QLineEdit(self.centralwidget)
        self.line_in7.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in7.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in7.setReadOnly(True)
        self.line_in7.setObjectName(_fromUtf8("line_in7"))
        self.gridLayout.addWidget(self.line_in7, 1, 0, 1, 1)
        self.line_in11 = QtGui.QLineEdit(self.centralwidget)
        self.line_in11.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in11.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in11.setReadOnly(True)
        self.line_in11.setObjectName(_fromUtf8("line_in11"))
        self.gridLayout.addWidget(self.line_in11, 1, 4, 1, 1)
        self.line_in16 = QtGui.QLineEdit(self.centralwidget)
        self.line_in16.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in16.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in16.setObjectName(_fromUtf8("line_in16"))
        self.gridLayout.addWidget(self.line_in16, 2, 3, 1, 1)
        self.line_in15 = QtGui.QLineEdit(self.centralwidget)
        self.line_in15.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in15.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in15.setObjectName(_fromUtf8("line_in15"))
        self.gridLayout.addWidget(self.line_in15, 2, 2, 1, 1)
        self.line_in5 = QtGui.QLineEdit(self.centralwidget)
        self.line_in5.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in5.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in5.setReadOnly(True)
        self.line_in5.setObjectName(_fromUtf8("line_in5"))
        self.gridLayout.addWidget(self.line_in5, 0, 4, 1, 1)
        self.line_in12 = QtGui.QLineEdit(self.centralwidget)
        self.line_in12.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in12.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in12.setReadOnly(True)
        self.line_in12.setObjectName(_fromUtf8("line_in12"))
        self.gridLayout.addWidget(self.line_in12, 1, 5, 1, 1)
        self.line_in6 = QtGui.QLineEdit(self.centralwidget)
        self.line_in6.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in6.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in6.setReadOnly(True)
        self.line_in6.setObjectName(_fromUtf8("line_in6"))
        self.gridLayout.addWidget(self.line_in6, 0, 5, 1, 1)
        self.line_in8 = QtGui.QLineEdit(self.centralwidget)
        self.line_in8.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in8.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in8.setReadOnly(True)
        self.line_in8.setObjectName(_fromUtf8("line_in8"))
        self.gridLayout.addWidget(self.line_in8, 1, 1, 1, 1)
        self.line_in3 = QtGui.QLineEdit(self.centralwidget)
        self.line_in3.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in3.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in3.setReadOnly(True)
        self.line_in3.setObjectName(_fromUtf8("line_in3"))
        self.gridLayout.addWidget(self.line_in3, 0, 2, 1, 1)
        self.line_in9 = QtGui.QLineEdit(self.centralwidget)
        self.line_in9.setMinimumSize(QtCore.QSize(0, 50))
        self.line_in9.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in9.setReadOnly(True)
        self.line_in9.setObjectName(_fromUtf8("line_in9"))
        self.gridLayout.addWidget(self.line_in9, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 8, 0, 1, 2)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 1, 0, 1, 2)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 5, 0, 2, 2)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_3.addWidget(self.line_5, 9, 0, 1, 2)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
                                              "font: 10pt \"Franklin Gothic Medium\";\n"
                                              "color: rgb(85, 255, 255);"))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_3.addWidget(self.textEdit, 14, 0, 1, 2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chk_out6 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out6.setObjectName(_fromUtf8("chk_out6"))
        self.gridLayout_2.addWidget(self.chk_out6, 0, 7, 1, 1)
        self.chk_out1 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out1.setObjectName(_fromUtf8("chk_out1"))
        self.gridLayout_2.addWidget(self.chk_out1, 0, 0, 1, 1)
        self.chk_out11 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out11.setObjectName(_fromUtf8("chk_out11"))
        self.gridLayout_2.addWidget(self.chk_out11, 3, 5, 1, 1)
        self.chk_out8 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out8.setObjectName(_fromUtf8("chk_out8"))
        self.gridLayout_2.addWidget(self.chk_out8, 3, 1, 1, 1)
        self.chk_out10 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out10.setObjectName(_fromUtf8("chk_out10"))
        self.gridLayout_2.addWidget(self.chk_out10, 3, 4, 1, 1)
        self.chk_out7 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out7.setObjectName(_fromUtf8("chk_out7"))
        self.gridLayout_2.addWidget(self.chk_out7, 3, 0, 1, 1)
        self.chk_out9 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out9.setObjectName(_fromUtf8("chk_out9"))
        self.gridLayout_2.addWidget(self.chk_out9, 3, 2, 1, 1)
        self.chk_out5 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out5.setObjectName(_fromUtf8("chk_out5"))
        self.gridLayout_2.addWidget(self.chk_out5, 0, 5, 1, 1)
        self.chk_out2 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out2.setObjectName(_fromUtf8("chk_out2"))
        self.gridLayout_2.addWidget(self.chk_out2, 0, 1, 1, 1)
        self.chk_out3 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out3.setObjectName(_fromUtf8("chk_out3"))
        self.gridLayout_2.addWidget(self.chk_out3, 0, 2, 1, 1)
        self.chk_out4 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out4.setObjectName(_fromUtf8("chk_out4"))
        self.gridLayout_2.addWidget(self.chk_out4, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 7, 1, 1)
        self.chk_out12 = QtGui.QCheckBox(self.centralwidget)
        self.chk_out12.setObjectName(_fromUtf8("chk_out12"))
        self.gridLayout_2.addWidget(self.chk_out12, 3, 7, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 10, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
                                             "font: 10pt \"Agency FB\";"))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1554, 37))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "garment_tester_demo", None))
        self.btn_fix_check.setText(_translate("MainWindow", "治具检测", None))
        self.btn_roll_test.setText(_translate("MainWindow", "滚压测试", None))
        self.btn_acc_test.setText(_translate("MainWindow", "振动测试", None))
        self.btn_test_finished.setText(_translate("MainWindow", "测试结束", None))
        self.btn_auto_test.setText(_translate("MainWindow", "自动测试", None))
        self.btn_loop_test.setText(_translate("MainWindow", "循环测试", None))
        self.btn_reset.setText(_translate("MainWindow", "复位", None))
        self.pushButton_10.setText(_translate("MainWindow", "下压电机复位", None))
        self.pushButton_11.setText(_translate("MainWindow", "滚动电机复位", None))
        self.btn_press_home.setText(_translate("MainWindow", "下压电机home", None))
        self.btn_roll_home.setText(_translate("MainWindow", "滚动电机home", None))
        self.pushButton_2.setText(_translate("MainWindow", "MCU采集", None))
        self.pushButton.setText(_translate("MainWindow", "loadcell采集", None))
        self.pushButton_28.setText(_translate("MainWindow", "Acc采集", None))
        self.label_13.setText(_translate("MainWindow", " 电机端口:", None))
        self.label.setText(_translate("MainWindow", "loadcell:", None))
        self.label_5.setText(_translate("MainWindow", "ACC端口:", None))
        self.label_6.setText(_translate("MainWindow", "IO端口:", None))
        self.label_2.setText(_translate("MainWindow", "MCU:", None))
        self.label_15.setText(_translate("MainWindow", "下压电机地址:", None))
        self.label_12.setText(_translate("MainWindow", "滚压电机地址:", None))
        self.label_7.setText(_translate("MainWindow", "滚动位置:", None))
        self.pushButton_3.setText(_translate("MainWindow", "移动", None))
        self.label_9.setText(_translate("MainWindow", "下压位置:", None))
        self.pushButton_6.setText(_translate("MainWindow", "下 压", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>滚动长度:</p></body></html>", None))
        self.pushButton_8.setText(_translate("MainWindow", "滚 动", None))
        self.label_10.setText(_translate("MainWindow", "振动器位置:", None))
        self.pushButton_7.setText(_translate("MainWindow", "移动", None))
        self.btn_save.setText(_translate("MainWindow", "保存参数", None))
        self.line_in10.setText(_translate("MainWindow", "夹爪气缸松开", None))
        self.line_in1.setText(_translate("MainWindow", "急停按钮", None))
        self.line_in14.setText(_translate("MainWindow", "安全光栅", None))
        self.lline_in4.setText(_translate("MainWindow", "复位按钮", None))
        self.line_in13.setText(_translate("MainWindow", "真空检测", None))
        self.line_in2.setText(_translate("MainWindow", "启动按钮1", None))
        self.line_in7.setText(_translate("MainWindow", "张紧气缸拉紧", None))
        self.line_in11.setText(_translate("MainWindow", "滚压驱动器报警", None))
        self.line_in16.setText(_translate("MainWindow", "产品检测光电开关", None))
        self.line_in15.setText(_translate("MainWindow", "脚踏开关", None))
        self.line_in5.setText(_translate("MainWindow", "加速度无杆气缸上位", None))
        self.line_in12.setText(_translate("MainWindow", "下压驱动器报警", None))
        self.line_in6.setText(_translate("MainWindow", "加速度无杆气缸下位", None))
        self.line_in8.setText(_translate("MainWindow", "张紧气缸放松", None))
        self.line_in3.setText(_translate("MainWindow", "启动按钮2", None))
        self.line_in9.setText(_translate("MainWindow", "夹爪气缸夹紧", None))
        self.chk_out6.setText(_translate("MainWindow", "蜂鸣器", None))
        self.chk_out1.setText(_translate("MainWindow", "启动指示灯", None))
        self.chk_out11.setText(_translate("MainWindow", "真空阀开关", None))
        self.chk_out8.setText(_translate("MainWindow", "加速度无杆气缸电磁阀下", None))
        self.chk_out10.setText(_translate("MainWindow", "夹爪气缸", None))
        self.chk_out7.setText(_translate("MainWindow", "加速度无杆气缸电磁阀上", None))
        self.chk_out9.setText(_translate("MainWindow", "张紧气缸", None))
        self.chk_out5.setText(_translate("MainWindow", "三色灯(蓝）", None))
        self.chk_out2.setText(_translate("MainWindow", "复位指示灯", None))
        self.chk_out3.setText(_translate("MainWindow", "三色灯(绿）", None))
        self.chk_out4.setText(_translate("MainWindow", "三色灯(红）", None))
        self.chk_out12.setText(_translate("MainWindow", "清loadcell", None))
        self.label_4.setText(
            _translate("MainWindow", "<html><head/><body><p>灰色表示未产生信号，绿色表示产生信号</p></body></html>", None))

if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint)
    ui.show()
    sys.exit(app.exec_())