# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hely\he\Pyprojects\IBU2Solution\Forms\untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class PLineui(QtGui.QWidget):
    
    def __init__(self, parent=None):
        super(PLineui, self).__init__(parent)
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1421, 703)
        Form.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setMargin(2)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lab_line11 = QtGui.QLabel(Form)
        self.lab_line11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line11.setObjectName(_fromUtf8("lab_line11"))
        self.gridLayout.addWidget(self.lab_line11, 2, 12, 1, 1)
        self.lab_line3 = QtGui.QLabel(Form)
        self.lab_line3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line3.setObjectName(_fromUtf8("lab_line3"))
        self.gridLayout.addWidget(self.lab_line3, 2, 4, 1, 1)
        self.lab_line8 = QtGui.QLabel(Form)
        self.lab_line8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line8.setObjectName(_fromUtf8("lab_line8"))
        self.gridLayout.addWidget(self.lab_line8, 2, 9, 1, 1)
        self.lab_line10 = QtGui.QLabel(Form)
        self.lab_line10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line10.setObjectName(_fromUtf8("lab_line10"))
        self.gridLayout.addWidget(self.lab_line10, 2, 11, 1, 1)
        self.lab_line7 = QtGui.QLabel(Form)
        self.lab_line7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line7.setObjectName(_fromUtf8("lab_line7"))
        self.gridLayout.addWidget(self.lab_line7, 2, 8, 1, 1)
        self.lab_line6 = QtGui.QLabel(Form)
        self.lab_line6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line6.setObjectName(_fromUtf8("lab_line6"))
        self.gridLayout.addWidget(self.lab_line6, 2, 7, 1, 1)
        self.lab_line4 = QtGui.QLabel(Form)
        self.lab_line4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line4.setObjectName(_fromUtf8("lab_line4"))
        self.gridLayout.addWidget(self.lab_line4, 2, 5, 1, 1)
        self.lab_line9 = QtGui.QLabel(Form)
        self.lab_line9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line9.setObjectName(_fromUtf8("lab_line9"))
        self.gridLayout.addWidget(self.lab_line9, 2, 10, 1, 1)
        self.lab_line0 = QtGui.QLabel(Form)
        self.lab_line0.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line0.setObjectName(_fromUtf8("lab_line0"))
        self.gridLayout.addWidget(self.lab_line0, 2, 0, 1, 1)
        self.lab_line2 = QtGui.QLabel(Form)
        self.lab_line2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line2.setObjectName(_fromUtf8("lab_line2"))
        self.gridLayout.addWidget(self.lab_line2, 2, 3, 1, 1)
        self.lab_line5 = QtGui.QLabel(Form)
        self.lab_line5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line5.setObjectName(_fromUtf8("lab_line5"))
        self.gridLayout.addWidget(self.lab_line5, 2, 6, 1, 1)
        self.lab_line1 = QtGui.QLabel(Form)
        self.lab_line1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lab_line1.setObjectName(_fromUtf8("lab_line1"))
        self.gridLayout.addWidget(self.lab_line1, 2, 1, 1, 1)
        self.widget_lin8 = QtGui.QWidget(Form)
        self.widget_lin8.setObjectName(_fromUtf8("widget_lin8"))
        self.gridLayout_21 = QtGui.QGridLayout(self.widget_lin8)
        self.gridLayout_21.setMargin(0)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.grid_lin8 = QtGui.QGridLayout()
        self.grid_lin8.setObjectName(_fromUtf8("grid_lin8"))
        self.gridLayout_21.addLayout(self.grid_lin8, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin8, 0, 9, 1, 1)
        self.widget_lin1 = QtGui.QWidget(Form)
        self.widget_lin1.setObjectName(_fromUtf8("widget_lin1"))
        self.gridLayout_7 = QtGui.QGridLayout(self.widget_lin1)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.grid_lin1 = QtGui.QGridLayout()
        self.grid_lin1.setObjectName(_fromUtf8("grid_lin1"))
        self.gridLayout_7.addLayout(self.grid_lin1, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin1, 0, 1, 1, 1)
        self.widget_lin2 = QtGui.QWidget(Form)
        self.widget_lin2.setObjectName(_fromUtf8("widget_lin2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.widget_lin2)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.grid_lin2 = QtGui.QGridLayout()
        self.grid_lin2.setObjectName(_fromUtf8("grid_lin2"))
        self.gridLayout_9.addLayout(self.grid_lin2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin2, 0, 3, 1, 1)
        self.widget_lin4 = QtGui.QWidget(Form)
        self.widget_lin4.setObjectName(_fromUtf8("widget_lin4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.widget_lin4)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.grid_lin4 = QtGui.QGridLayout()
        self.grid_lin4.setObjectName(_fromUtf8("grid_lin4"))
        self.gridLayout_12.addLayout(self.grid_lin4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin4, 0, 5, 1, 1)
        self.widget_lin0 = QtGui.QWidget(Form)
        self.widget_lin0.setObjectName(_fromUtf8("widget_lin0"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_lin0)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.grid_lin0 = QtGui.QGridLayout()
        self.grid_lin0.setObjectName(_fromUtf8("grid_lin0"))
        self.gridLayout_4.addLayout(self.grid_lin0, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin0, 0, 0, 1, 1)
        self.widget_lin6 = QtGui.QWidget(Form)
        self.widget_lin6.setObjectName(_fromUtf8("widget_lin6"))
        self.gridLayout_16 = QtGui.QGridLayout(self.widget_lin6)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.grid_lin6 = QtGui.QGridLayout()
        self.grid_lin6.setObjectName(_fromUtf8("grid_lin6"))
        self.gridLayout_16.addLayout(self.grid_lin6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin6, 0, 7, 1, 1)
        self.widget_8 = QtGui.QWidget(Form)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.gridLayout_19 = QtGui.QGridLayout(self.widget_8)
        self.gridLayout_19.setMargin(0)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.grid_lin7 = QtGui.QGridLayout()
        self.grid_lin7.setObjectName(_fromUtf8("grid_lin7"))
        self.gridLayout_19.addLayout(self.grid_lin7, 0, 0, 1, 1)
        self.widget_lin8.raise_()
        self.gridLayout.addWidget(self.widget_8, 0, 8, 1, 1)
        self.widget_lin5 = QtGui.QWidget(Form)
        self.widget_lin5.setObjectName(_fromUtf8("widget_lin5"))
        self.gridLayout_14 = QtGui.QGridLayout(self.widget_lin5)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.grid_lin5 = QtGui.QGridLayout()
        self.grid_lin5.setObjectName(_fromUtf8("grid_lin5"))
        self.gridLayout_14.addLayout(self.grid_lin5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin5, 0, 6, 1, 1)
        self.widget_lin3 = QtGui.QWidget(Form)
        self.widget_lin3.setObjectName(_fromUtf8("widget_lin3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_lin3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.grid_lin3 = QtGui.QGridLayout()
        self.grid_lin3.setObjectName(_fromUtf8("grid_lin3"))
        self.horizontalLayout_3.addLayout(self.grid_lin3)
        self.gridLayout.addWidget(self.widget_lin3, 0, 4, 1, 1)
        self.widget_lin9 = QtGui.QWidget(Form)
        self.widget_lin9.setObjectName(_fromUtf8("widget_lin9"))
        self.gridLayout_23 = QtGui.QGridLayout(self.widget_lin9)
        self.gridLayout_23.setMargin(0)
        self.gridLayout_23.setSpacing(0)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.grid_lin9 = QtGui.QGridLayout()
        self.grid_lin9.setObjectName(_fromUtf8("grid_lin9"))
        self.gridLayout_23.addLayout(self.grid_lin9, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin9, 0, 10, 1, 1)
        self.widget_lin10 = QtGui.QWidget(Form)
        self.widget_lin10.setObjectName(_fromUtf8("widget_lin10"))
        self.gridLayout_25 = QtGui.QGridLayout(self.widget_lin10)
        self.gridLayout_25.setMargin(0)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.grid_lin10 = QtGui.QGridLayout()
        self.grid_lin10.setObjectName(_fromUtf8("grid_lin10"))
        self.gridLayout_25.addLayout(self.grid_lin10, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin10, 0, 11, 1, 1)
        self.widget_lin11 = QtGui.QWidget(Form)
        self.widget_lin11.setObjectName(_fromUtf8("widget_lin11"))
        self.gridLayout_27 = QtGui.QGridLayout(self.widget_lin11)
        self.gridLayout_27.setMargin(0)
        self.gridLayout_27.setSpacing(0)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.grid_lin11 = QtGui.QGridLayout()
        self.grid_lin11.setObjectName(_fromUtf8("grid_lin11"))
        self.gridLayout_27.addLayout(self.grid_lin11, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_lin11, 0, 12, 1, 1)
        self.gridLayout.setRowStretch(0, 20)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "line value changedr", None))
        self.lab_line11.setText(_translate("Form", "12-0", None))
        self.lab_line3.setText(_translate("Form", "4-0", None))
        self.lab_line8.setText(_translate("Form", "9-0", None))
        self.lab_line10.setText(_translate("Form", "11-0", None))
        self.lab_line7.setText(_translate("Form", "8-0", None))
        self.lab_line6.setText(_translate("Form", "7-0", None))
        self.lab_line4.setText(_translate("Form", "5-0", None))
        self.lab_line9.setText(_translate("Form", "10-0", None))
        self.lab_line0.setText(_translate("Form", "1-0", None))
        self.lab_line2.setText(_translate("Form", "3-0", None))
        self.lab_line5.setText(_translate("Form", "6-0", None))
        self.lab_line1.setText(_translate("Form", "2-0", None))


